# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.define "slave", autostart: true do |slave|
    slave.vm.box = "ansible/slave"
    slave.vm.network "private_network", ip: "192.168.147.11", virtualbox__intnet: true
  end

  config.vm.define "master", autostart: true do |master|
    master.vm.box = "ansible/master"
    master.vm.network "private_network", ip: "192.168.147.10", virtualbox__intnet: true
    master.vm.provision "shell", inline: <<-SHELL
      sudo su
      export ANSIBLE_HOST_KEY_CHECKING=False
      ansible --inventory "192.168.147.11," \
              --module-name "ansible.builtin.setup" \
              all
    SHELL
  end

end
